version: "3.8"

networks:
  bot-network:

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/src/app
    command:
      - sh
    tty: true
    ports:
      - 9300:9229
    env_file:
      - .env
      - .env.redis
    networks:
      bot-network:
        aliases:
          - "api"

  redis:
    image: redis
    networks:
      bot-network:
        aliases:
          - "redis"