name: Build Docker Image & Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    runs-on: Linux
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: make ci-build
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

  deploy:
    runs-on: Linux
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to machine
        run: make ci-deploy
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY_LOCATION: ${{ secrets.SSH_KEY_LOCATION }}
